"""add shortened url table

Revision ID: e100dc406185
Revises:
Create Date: 2025-03-27 22:43:35.980791

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "e100dc406185"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shortened_urls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alias_text", sa.VARCHAR(), nullable=False),
        sa.Column("original_url_text", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shortened_urls_alias_text"),
        "shortened_urls",
        ["alias_text"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_shortened_urls_alias_text"), table_name="shortened_urls"
    )
    op.drop_table("shortened_urls")
    # ### end Alembic commands ###
